#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LakesideLoungeAndroid.Resource", IsApplication=true)]

namespace LakesideLoungeAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::BensJson.Resource.String.ApplicationName = global::LakesideLoungeAndroid.Resource.String.ApplicationName;
			global::BensJson.Resource.String.Hello = global::LakesideLoungeAndroid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Completed = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Confirm = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Delete = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Edit = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Forward = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Locked = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Logo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Pen = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int PopupBorder = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int VariationsListBorder = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ViewComponents = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
