//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LakesideLoungeDB {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Lakeside : global::System.Configuration.ApplicationSettingsBase {
        
        private static Lakeside defaultInstance = ((Lakeside)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Lakeside())));
        
        public static Lakeside Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Ben")]
        public string UserPath {
            get {
                return ((string)(this["UserPath"]));
            }
            set {
                this["UserPath"] = value;
            }
        }
    }
}
